# Generated by Django 3.2.4 on 2021-07-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='headingimg',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
